{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "a54edbc7-dd0e-48b1-a481-60a751318cb8",
   "metadata": {},
   "source": [
    "Run !pip install ipympl and !pip install PyQt5 only if need to install\n",
    "To run, remove the \"#\" sign"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b0ff3afd-8393-48f1-aa60-50851aa02265",
   "metadata": {},
   "outputs": [],
   "source": [
    " # !pip install ipympl"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "df4998b1-af9d-4e02-8d67-4ffc13a702cd",
   "metadata": {},
   "outputs": [],
   "source": [
    " # !pip install PyQt5"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4b3839e7-628f-44ba-8634-8eaab5886b8f",
   "metadata": {},
   "source": [
    "%matplotlib widget\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "360135af-e2b1-469a-ab57-b1bfddaea111",
   "metadata": {},
   "outputs": [],
   "source": [
    "%matplotlib qt\n",
    "import json\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.patches import Rectangle\n",
    "from matplotlib.widgets import TextBox\n",
    "\n",
    "# Closes all previously opened figures to ensure only ONE window appears\n",
    "plt.close('all')\n",
    "\n",
    "class FullFlightProfileEditor:\n",
    "    def __init__(self):\n",
    "        # 1. Initial coordinates: [time_mins, altitude_k_ft]\n",
    "        self.points = [\n",
    "            [1.0, 0.0], [7.0, 0.0], [12.0, 0.0], [15.0, 0.0],\n",
    "            [23.0, 40.0], [39.0, 40.0], [41.0, 26.0], [45.0, 0.0],\n",
    "            [54.0, 0.0], [55.0, 5.0], [65.0, 36.0], [82.0, 36.0],\n",
    "            [83.0, 33.0], [91.0, 0.0], [99.0, 5.0], [104.0, 5.0],\n",
    "            [106.0, 1.5], [116.0, 0.0]\n",
    "        ]\n",
    "\n",
    "        initial_labels = {\n",
    "            0: \"ENGINES RUNNING\", 1: \"180° TURN F/O & CAPT\",\n",
    "            2: \"DELAYED WINGTIPS EXTENSION\", 3: \"HUD TAKEOFF\",\n",
    "            4: \"VSD DEMO\", 6: \"ILS\", 8: \"HUD TAKEOFF\",\n",
    "            9: \"ENG FAIL R (SEVERE DAMAGE)\", 12: \"RNAV Y (LPV MINIMA)\",\n",
    "            13: \"OEI G/A & M/A\", 14: \"[ ] FUEL IMBALANCE\",\n",
    "            15: \"[ ] WINGTIPS DRIVE FAULT\", 16: \"OEI MANUAL ILS\",\n",
    "            17: \"AFTER LANDING\"\n",
    "        }\n",
    "        self.labels = [initial_labels.get(i, \"\") for i in range(len(self.points))]\n",
    "\n",
    "        # 2. Figure Setup\n",
    "        self.fig, self.ax = plt.subplots(figsize=(14, 8))\n",
    "        self.fig.canvas.manager.set_window_title(\"Flight Profile Editor\")\n",
    "        plt.subplots_adjust(bottom=0.14)\n",
    "        self.ax.set_facecolor(\"#d7ecf8\")\n",
    "        self.ax.set_xlim(-2, 126)\n",
    "        self.ax.set_ylim(-2, 72)\n",
    "        self.ax.set_xlabel(\"TIME (Mins)\", fontsize=11, fontweight=\"bold\", labelpad=8)\n",
    "        self.ax.set_ylabel(\"ALTITUDE (x1,000)\", fontsize=11, fontweight=\"bold\", labelpad=8)\n",
    "\n",
    "        # 3. Draggable Bands (Constructed as Rectangles for clean updating)\n",
    "        self.bands_data = [\n",
    "            {\"left\": 12.0, \"right\": 26.0},\n",
    "            {\"left\": 81.0, \"right\": 93.0}\n",
    "        ]\n",
    "        self.band_patches = []\n",
    "        for b in self.bands_data:\n",
    "            rect = Rectangle(\n",
    "                (b[\"left\"], -5), b[\"right\"] - b[\"left\"], 80,\n",
    "                color=\"#b9e0f7\", alpha=0.65, zorder=1\n",
    "            )\n",
    "            self.ax.add_patch(rect)\n",
    "            self.band_patches.append(rect)\n",
    "\n",
    "        # 4. Draggable FL Labels\n",
    "        self.fl_labels_data = [\n",
    "            {\"text\": \"FL 360\", \"pos\": [23.0, 34.0]},\n",
    "            {\"text\": \"FL 360\", \"pos\": [65.0, 34.0]}\n",
    "        ]\n",
    "        self.fl_artists = [\n",
    "            self.ax.text(fl[\"pos\"][0], fl[\"pos\"][1], fl[\"text\"],\n",
    "                         color=\"red\", fontweight=\"bold\", fontsize=10, zorder=6)\n",
    "            for fl in self.fl_labels_data\n",
    "        ]\n",
    "\n",
    "        # 5. Profile Line & Scatter Points\n",
    "        pts_np = np.array(self.points)\n",
    "        self.line, = self.ax.plot(pts_np[:, 0], pts_np[:, 1], color=\"#17557d\", lw=2.5, zorder=3)\n",
    "        self.scatter = self.ax.scatter(pts_np[:, 0], pts_np[:, 1], color=\"#17557d\", s=55, zorder=4)\n",
    "\n",
    "        # Labels\n",
    "        self.text_artists = []\n",
    "        self._init_labels()\n",
    "\n",
    "        # Tooltip HUD\n",
    "        self.tooltip = self.ax.annotate(\n",
    "            \"\", xy=(0, 0), xytext=(12, 12), textcoords=\"offset points\",\n",
    "            bbox=dict(boxstyle=\"round,pad=0.3\", fc=\"#202020\", ec=\"none\", alpha=0.85),\n",
    "            color=\"white\", fontsize=9, fontweight=\"bold\", zorder=10\n",
    "        )\n",
    "        self.tooltip.set_visible(False)\n",
    "\n",
    "        # 6. Integrated Label Input Box\n",
    "        box_ax = plt.axes([0.30, 0.025, 0.45, 0.045])\n",
    "        self.textbox = TextBox(box_ax, 'Edit Selected Label: ', initial='')\n",
    "        self.textbox.on_submit(self.on_text_submit)\n",
    "\n",
    "        # Interaction State Variables\n",
    "        self.active_editing = None\n",
    "        self.selected_point_idx = None\n",
    "        self.selected_segment_idx = None\n",
    "        self.selected_fl_idx = None\n",
    "        self.selected_band_idx = None\n",
    "        self.band_drag_mode = None  # 'move', 'left_edge', 'right_edge'\n",
    "        self.drag_start = None\n",
    "\n",
    "        # Events\n",
    "        self.fig.canvas.mpl_connect('button_press_event', self.on_press)\n",
    "        self.fig.canvas.mpl_connect('motion_notify_event', self.on_motion)\n",
    "        self.fig.canvas.mpl_connect('button_release_event', self.on_release)\n",
    "        self.fig.canvas.mpl_connect('key_press_event', self.on_key_press)\n",
    "\n",
    "    def _init_labels(self):\n",
    "        for ann in self.text_artists:\n",
    "            ann.remove()\n",
    "        self.text_artists = []\n",
    "        for i, text in enumerate(self.labels):\n",
    "            ann = self.ax.annotate(\n",
    "                text, (self.points[i][0], self.points[i][1]),\n",
    "                xytext=(0, 10), textcoords=\"offset points\",\n",
    "                rotation=90, color=\"#005596\", fontsize=8.5,\n",
    "                fontweight=\"semibold\", ha=\"center\", va=\"bottom\", zorder=5\n",
    "            )\n",
    "            self.text_artists.append(ann)\n",
    "\n",
    "    def _distance_to_segment(self, p, a, b):\n",
    "        ab = b - a\n",
    "        norm_ab = np.linalg.norm(ab)\n",
    "        if norm_ab == 0:\n",
    "            return np.linalg.norm(p - a)\n",
    "        t = np.clip(np.dot(p - a, ab) / (norm_ab ** 2), 0.0, 1.0)\n",
    "        proj = a + t * ab\n",
    "        return np.linalg.norm(p - proj)\n",
    "\n",
    "    def on_text_submit(self, new_text):\n",
    "        if not self.active_editing:\n",
    "            return\n",
    "        target, idx = self.active_editing\n",
    "        if target == 'point' and idx < len(self.labels):\n",
    "            self.labels[idx] = new_text\n",
    "            self.text_artists[idx].set_text(new_text)\n",
    "        elif target == 'fl' and idx < len(self.fl_labels_data):\n",
    "            self.fl_labels_data[idx][\"text\"] = new_text\n",
    "            self.fl_artists[idx].set_text(new_text)\n",
    "        self.fig.canvas.draw_idle()\n",
    "\n",
    "    def on_press(self, event):\n",
    "        if event.inaxes != self.ax:\n",
    "            return\n",
    "\n",
    "        click_xy = np.array([event.x, event.y])\n",
    "        pts_screen = self.ax.transData.transform(np.array(self.points))\n",
    "        dists = np.linalg.norm(pts_screen - click_xy, axis=1)\n",
    "        min_idx = np.argmin(dists)\n",
    "\n",
    "        # 1. DELETE POINT (Right-Click)\n",
    "        if event.button == 3:\n",
    "            if dists[min_idx] < 12.0 and len(self.points) > 2:\n",
    "                del self.points[min_idx]\n",
    "                del self.labels[min_idx]\n",
    "                self.active_editing = None\n",
    "                self.textbox.set_val(\"\")\n",
    "                self._init_labels()\n",
    "                self.update_canvas()\n",
    "            return\n",
    "\n",
    "        # 2. ADD POINT (Double-Click on a line)\n",
    "        if event.button == 1 and event.dblclick:\n",
    "            for i in range(len(self.points) - 1):\n",
    "                if self._distance_to_segment(click_xy, pts_screen[i], pts_screen[i + 1]) < 10.0:\n",
    "                    new_pt = [float(event.xdata), max(0.0, float(event.ydata))]\n",
    "                    insert_idx = i + 1\n",
    "                    self.points.insert(insert_idx, new_pt)\n",
    "                    self.labels.insert(insert_idx, \"WAYPOINT\")\n",
    "                    self._init_labels()\n",
    "                    self.update_canvas()\n",
    "                    self.active_editing = ('point', insert_idx)\n",
    "                    self.textbox.set_val(self.labels[insert_idx])\n",
    "                    return\n",
    "\n",
    "        if event.button != 1:\n",
    "            return\n",
    "\n",
    "        # 3. CLICKING FL LABELS\n",
    "        for idx, fl_artist in enumerate(self.fl_artists):\n",
    "            if fl_artist.get_window_extent(self.fig.canvas.get_renderer()).contains(event.x, event.y):\n",
    "                self.active_editing = ('fl', idx)\n",
    "                self.textbox.set_val(self.fl_labels_data[idx][\"text\"])\n",
    "                self.selected_fl_idx = idx\n",
    "                self.drag_start = (event.xdata, event.ydata)\n",
    "                return\n",
    "\n",
    "        # 4. CLICKING WAYPOINT DOTS\n",
    "        if dists[min_idx] < 12.0:\n",
    "            self.active_editing = ('point', min_idx)\n",
    "            self.textbox.set_val(self.labels[min_idx])\n",
    "            self.selected_point_idx = min_idx\n",
    "            self._show_tooltip(self.points[min_idx][0], self.points[min_idx][1])\n",
    "            return\n",
    "\n",
    "        # 5. CLICKING LINE SEGMENTS\n",
    "        for i in range(len(self.points) - 1):\n",
    "            if self._distance_to_segment(click_xy, pts_screen[i], pts_screen[i + 1]) < 8.0:\n",
    "                self.selected_segment_idx = i\n",
    "                self.drag_start = (event.xdata, event.ydata)\n",
    "                return\n",
    "\n",
    "        # 6. CLICKING / RESIZING BANDS\n",
    "        edge_thresh = 2.0  # Time units threshold for border resizing\n",
    "        for idx, band in enumerate(self.bands_data):\n",
    "            if abs(event.xdata - band[\"left\"]) <= edge_thresh:\n",
    "                self.selected_band_idx = idx\n",
    "                self.band_drag_mode = 'left_edge'\n",
    "                self.drag_start = (event.xdata, event.ydata)\n",
    "                self._show_band_tooltip(event.xdata, event.ydata, f\"Band {idx+1}: Left Edge\")\n",
    "                return\n",
    "            elif abs(event.xdata - band[\"right\"]) <= edge_thresh:\n",
    "                self.selected_band_idx = idx\n",
    "                self.band_drag_mode = 'right_edge'\n",
    "                self.drag_start = (event.xdata, event.ydata)\n",
    "                self._show_band_tooltip(event.xdata, event.ydata, f\"Band {idx+1}: Right Edge\")\n",
    "                return\n",
    "            elif band[\"left\"] <= event.xdata <= band[\"right\"]:\n",
    "                self.selected_band_idx = idx\n",
    "                self.band_drag_mode = 'move'\n",
    "                self.drag_start = (event.xdata, event.ydata)\n",
    "                self._show_band_tooltip(event.xdata, event.ydata, f\"Band {idx+1}: Moving\")\n",
    "                return\n",
    "\n",
    "    def on_motion(self, event):\n",
    "        if event.inaxes != self.ax:\n",
    "            return\n",
    "\n",
    "        # Move FL label\n",
    "        if self.selected_fl_idx is not None:\n",
    "            dx = event.xdata - self.drag_start[0]\n",
    "            dy = event.ydata - self.drag_start[1]\n",
    "            pos = self.fl_labels_data[self.selected_fl_idx][\"pos\"]\n",
    "            pos[0] += dx\n",
    "            pos[1] += dy\n",
    "            self.fl_artists[self.selected_fl_idx].set_position((pos[0], pos[1]))\n",
    "            self.drag_start = (event.xdata, event.ydata)\n",
    "            self.fig.canvas.draw_idle()\n",
    "            return\n",
    "\n",
    "        # Move or Resize Bands\n",
    "        if self.selected_band_idx is not None:\n",
    "            dx = event.xdata - self.drag_start[0]\n",
    "            band = self.bands_data[self.selected_band_idx]\n",
    "            \n",
    "            if self.band_drag_mode == 'move':\n",
    "                band[\"left\"] += dx\n",
    "                band[\"right\"] += dx\n",
    "                self._show_band_tooltip(event.xdata, event.ydata, f\"Band: [{band['left']:.1f} - {band['right']:.1f}]\")\n",
    "            elif self.band_drag_mode == 'left_edge':\n",
    "                if band[\"left\"] + dx < band[\"right\"] - 1.0:\n",
    "                    band[\"left\"] += dx\n",
    "                self._show_band_tooltip(band[\"left\"], event.ydata, f\"Left: {band['left']:.1f}m\")\n",
    "            elif self.band_drag_mode == 'right_edge':\n",
    "                if band[\"right\"] + dx > band[\"left\"] + 1.0:\n",
    "                    band[\"right\"] += dx\n",
    "                self._show_band_tooltip(band[\"right\"], event.ydata, f\"Right: {band['right']:.1f}m\")\n",
    "\n",
    "            self.drag_start = (event.xdata, event.ydata)\n",
    "            self._update_bands()\n",
    "            return\n",
    "\n",
    "        # Move single dot\n",
    "        if self.selected_point_idx is not None:\n",
    "            idx = self.selected_point_idx\n",
    "            new_x = float(event.xdata)\n",
    "            new_y = max(0.0, float(event.ydata))\n",
    "\n",
    "            min_x = self.points[idx - 1][0] if idx > 0 else -2.0\n",
    "            max_x = self.points[idx + 1][0] if idx < len(self.points) - 1 else 125.0\n",
    "            new_x = np.clip(new_x, min_x + 0.05, max_x - 0.05)\n",
    "\n",
    "            self.points[idx] = [new_x, new_y]\n",
    "            self._show_tooltip(new_x, new_y)\n",
    "            self.update_canvas()\n",
    "\n",
    "        # Move line segment\n",
    "        elif self.selected_segment_idx is not None:\n",
    "            dx = event.xdata - self.drag_start[0]\n",
    "            dy = event.ydata - self.drag_start[1]\n",
    "            idx = self.selected_segment_idx\n",
    "\n",
    "            p1, p2 = self.points[idx], self.points[idx + 1]\n",
    "            if p1[1] + dy >= 0 and p2[1] + dy >= 0:\n",
    "                min_x = self.points[idx - 1][0] if idx > 0 else -2.0\n",
    "                max_x = self.points[idx + 2][0] if idx + 2 < len(self.points) else 125.0\n",
    "\n",
    "                if (p1[0] + dx > min_x) and (p2[0] + dx < max_x):\n",
    "                    self.points[idx] = [p1[0] + dx, p1[1] + dy]\n",
    "                    self.points[idx + 1] = [p2[0] + dx, p2[1] + dy]\n",
    "                    self.drag_start = (event.xdata, event.ydata)\n",
    "                    self.update_canvas()\n",
    "\n",
    "    def on_release(self, event):\n",
    "        self.selected_point_idx = None\n",
    "        self.selected_segment_idx = None\n",
    "        self.selected_fl_idx = None\n",
    "        self.selected_band_idx = None\n",
    "        self.band_drag_mode = None\n",
    "        self.drag_start = None\n",
    "        self.tooltip.set_visible(False)\n",
    "        self.fig.canvas.draw_idle()\n",
    "\n",
    "    def _show_tooltip(self, x, y):\n",
    "        self.tooltip.xy = (x, y)\n",
    "        self.tooltip.set_text(f\"T: {x:.1f}m\\nAlt: {y:.1f}k\")\n",
    "        self.tooltip.set_visible(True)\n",
    "\n",
    "    def _show_band_tooltip(self, x, y, msg):\n",
    "        self.tooltip.xy = (x, y)\n",
    "        self.tooltip.set_text(msg)\n",
    "        self.tooltip.set_visible(True)\n",
    "\n",
    "    def _update_bands(self):\n",
    "        for idx, rect in enumerate(self.band_patches):\n",
    "            b = self.bands_data[idx]\n",
    "            rect.set_x(b[\"left\"])\n",
    "            rect.set_width(b[\"right\"] - b[\"left\"])\n",
    "        self.fig.canvas.draw_idle()\n",
    "\n",
    "    def on_key_press(self, event):\n",
    "        if event.key in ['s', 'S']:\n",
    "            export_data = {\n",
    "                \"points\": [\n",
    "                    {\"time_min\": round(p[0], 2), \"altitude_kft\": round(p[1], 2), \"label\": lbl}\n",
    "                    for p, lbl in zip(self.points, self.labels)\n",
    "                ],\n",
    "                \"bands\": [\n",
    "                    {\"left\": round(b[\"left\"], 2), \"right\": round(b[\"right\"], 2)}\n",
    "                    for b in self.bands_data\n",
    "                ],\n",
    "                \"fl_labels\": [\n",
    "                    {\"text\": fl[\"text\"], \"time_min\": round(fl[\"pos\"][0], 2), \"altitude_kft\": round(fl[\"pos\"][1], 2)}\n",
    "                    for fl in self.fl_labels_data\n",
    "                ]\n",
    "            }\n",
    "            with open(\"flight_profile.json\", \"w\") as f:\n",
    "                json.dump(export_data, f, indent=4)\n",
    "            print(\"Exported flight profile data to 'flight_profile.json'!\")\n",
    "\n",
    "    def update_canvas(self):\n",
    "        pts = np.array(self.points)\n",
    "        self.line.set_data(pts[:, 0], pts[:, 1])\n",
    "        self.scatter.set_offsets(pts)\n",
    "        for i, ann in enumerate(self.text_artists):\n",
    "            ann.xy = (self.points[i][0], self.points[i][1])\n",
    "        self.fig.canvas.draw_idle()\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    editor = FullFlightProfileEditor()\n",
    "    plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "2e3d66bf-89d2-4af0-be59-4c5de933629f",
   "metadata": {},
   "outputs": [],
   "source": [
    "%matplotlib qt\n",
    "import json\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import matplotlib.colors as mcolors\n",
    "\n",
    "class EnhancedFlightProfileEditor:\n",
    "    def __init__(self):\n",
    "        # Initial coordinates: [time_mins, altitude_k_ft]\n",
    "        self.points = [\n",
    "            [1.0, 0.0], [7.0, 0.0], [12.0, 0.0], [15.0, 0.0],\n",
    "            [23.0, 40.0], [39.0, 40.0], [41.0, 26.0], [45.0, 0.0],\n",
    "            [54.0, 0.0], [55.0, 5.0], [65.0, 36.0], [82.0, 36.0],\n",
    "            [83.0, 33.0], [91.0, 0.0], [99.0, 5.0], [104.0, 5.0],\n",
    "            [106.0, 1.5], [116.0, 0.0]\n",
    "        ]\n",
    "\n",
    "        # Labels attached by point index initially\n",
    "        initial_labels = {\n",
    "            0: \"ENGINES RUNNING\", 1: \"180° TURN F/O & CAPT\",\n",
    "            2: \"DELAYED WINGTIPS EXTENSION\", 3: \"HUD TAKEOFF\",\n",
    "            4: \"VSD DEMO\", 6: \"ILS\", 8: \"HUD TAKEOFF\",\n",
    "            9: \"ENG FAIL R (SEVERE DAMAGE)\", 12: \"RNAV Y (LPV MINIMA)\",\n",
    "            13: \"OEI G/A & M/A\", 14: \"[ ] FUEL IMBALANCE\",\n",
    "            15: \"[ ] WINGTIPS DRIVE FAULT\", 16: \"OEI MANUAL ILS\",\n",
    "            17: \"AFTER LANDING\"\n",
    "        }\n",
    "        self.labels = [initial_labels.get(i, \"\") for i in range(len(self.points))]\n",
    "\n",
    "        # Setup Figure & Styling\n",
    "        self.fig, self.ax = plt.subplots(figsize=(14, 8))\n",
    "        self.fig.canvas.manager.set_window_title(\"Interactive Flight Profile Editor\")\n",
    "        self.ax.set_facecolor(\"#d7ecf8\")\n",
    "        self.ax.set_xlim(-2, 126)\n",
    "        self.ax.set_ylim(-2, 72)\n",
    "        self.ax.set_xlabel(\"TIME (Mins)\", fontsize=11, fontweight=\"bold\", labelpad=8)\n",
    "        self.ax.set_ylabel(\"ALTITUDE (x1,000)\", fontsize=11, fontweight=\"bold\", labelpad=8)\n",
    "\n",
    "        # Draw shaded vertical flight operational bands\n",
    "        self._draw_background_bands()\n",
    "\n",
    "        # Altitude highlight labels (FL 360)\n",
    "        self.ax.text(23, 34, \"FL 360\", color=\"red\", fontweight=\"bold\", fontsize=10)\n",
    "        self.ax.text(65, 34, \"FL 360\", color=\"red\", fontweight=\"bold\", fontsize=10)\n",
    "\n",
    "        # Base plot lines and points\n",
    "        pts_np = np.array(self.points)\n",
    "        self.line, = self.ax.plot(pts_np[:, 0], pts_np[:, 1], color=\"#17557d\", lw=2.5, zorder=3)\n",
    "        self.scatter = self.ax.scatter(pts_np[:, 0], pts_np[:, 1], color=\"#17557d\", s=55, zorder=4)\n",
    "\n",
    "        # Text labels list\n",
    "        self.text_artists = []\n",
    "        self._init_labels()\n",
    "\n",
    "        # Live readout tooltip\n",
    "        self.tooltip = self.ax.annotate(\n",
    "            \"\", xy=(0, 0), xytext=(12, 12), textcoords=\"offset points\",\n",
    "            bbox=dict(boxstyle=\"round,pad=0.3\", fc=\"#202020\", ec=\"none\", alpha=0.85),\n",
    "            color=\"white\", fontsize=9, fontweight=\"bold\", zorder=10\n",
    "        )\n",
    "        self.tooltip.set_visible(False)\n",
    "\n",
    "        # Interaction tracking variables\n",
    "        self.selected_point_idx = None\n",
    "        self.selected_segment_idx = None\n",
    "        self.drag_start = None\n",
    "\n",
    "        # Connect canvas events\n",
    "        self.fig.canvas.mpl_connect('button_press_event', self.on_press)\n",
    "        self.fig.canvas.mpl_connect('motion_notify_event', self.on_motion)\n",
    "        self.fig.canvas.mpl_connect('button_release_event', self.on_release)\n",
    "        self.fig.canvas.mpl_connect('key_press_event', self.on_key_press)\n",
    "\n",
    "    def _draw_background_bands(self):\n",
    "        \"\"\"Draws soft gradient vertical zones matching reference flight charts.\"\"\"\n",
    "        bands = [(12, 26), (81, 93)]\n",
    "        for left, right in bands:\n",
    "            self.ax.axvspan(left, right, color=\"#b9e0f7\", alpha=0.65, zorder=1)\n",
    "\n",
    "    def _init_labels(self):\n",
    "        for ann in self.text_artists:\n",
    "            ann.remove()\n",
    "        self.text_artists = []\n",
    "        for i, text in enumerate(self.labels):\n",
    "            ann = self.ax.annotate(\n",
    "                text, (self.points[i][0], self.points[i][1]),\n",
    "                xytext=(0, 10), textcoords=\"offset points\",\n",
    "                rotation=90, color=\"#005596\", fontsize=8.5,\n",
    "                fontweight=\"semibold\", ha=\"center\", va=\"bottom\", zorder=5\n",
    "            )\n",
    "            self.text_artists.append(ann)\n",
    "\n",
    "    def _distance_to_segment(self, p, a, b):\n",
    "        ab = b - a\n",
    "        norm_ab = np.linalg.norm(ab)\n",
    "        if norm_ab == 0:\n",
    "            return np.linalg.norm(p - a), 0.0\n",
    "        t = np.clip(np.dot(p - a, ab) / (norm_ab ** 2), 0.0, 1.0)\n",
    "        proj = a + t * ab\n",
    "        return np.linalg.norm(p - proj), t\n",
    "\n",
    "    def on_press(self, event):\n",
    "        if event.inaxes != self.ax:\n",
    "            return\n",
    "\n",
    "        click_xy = np.array([event.x, event.y])\n",
    "        pts_screen = self.ax.transData.transform(np.array(self.points))\n",
    "        dists = np.linalg.norm(pts_screen - click_xy, axis=1)\n",
    "        min_idx = np.argmin(dists)\n",
    "\n",
    "        # --- RIGHT-CLICK: Delete Waypoint ---\n",
    "        if event.button == 3:\n",
    "            if dists[min_idx] < 12.0 and len(self.points) > 2:\n",
    "                del self.points[min_idx]\n",
    "                del self.labels[min_idx]\n",
    "                self._init_labels()\n",
    "                self.update_canvas()\n",
    "            return\n",
    "\n",
    "        # --- DOUBLE-CLICK LEFT: Add New Waypoint ---\n",
    "        if event.button == 1 and event.dblclick:\n",
    "            for i in range(len(self.points) - 1):\n",
    "                dist, t = self._distance_to_segment(click_xy, pts_screen[i], pts_screen[i + 1])\n",
    "                if dist < 10.0:\n",
    "                    new_point = [float(event.xdata), max(0.0, float(event.ydata))]\n",
    "                    self.points.insert(i + 1, new_point)\n",
    "                    self.labels.insert(i + 1, \"\")\n",
    "                    self._init_labels()\n",
    "                    self.update_canvas()\n",
    "                    return\n",
    "\n",
    "        # --- SINGLE-CLICK LEFT: Select for Dragging ---\n",
    "        if event.button == 1 and not event.dblclick:\n",
    "            if dists[min_idx] < 12.0:\n",
    "                self.selected_point_idx = min_idx\n",
    "                self._show_tooltip(self.points[min_idx][0], self.points[min_idx][1])\n",
    "                return\n",
    "\n",
    "            for i in range(len(self.points) - 1):\n",
    "                dist, _ = self._distance_to_segment(click_xy, pts_screen[i], pts_screen[i + 1])\n",
    "                if dist < 8.0:\n",
    "                    self.selected_segment_idx = i\n",
    "                    self.drag_start = (event.xdata, event.ydata)\n",
    "                    return\n",
    "\n",
    "    def on_motion(self, event):\n",
    "        if event.inaxes != self.ax:\n",
    "            return\n",
    "\n",
    "        # 1. Moving a single checkpoint\n",
    "        if self.selected_point_idx is not None:\n",
    "            idx = self.selected_point_idx\n",
    "            new_x = float(event.xdata)\n",
    "            new_y = max(0.0, float(event.ydata))  # Altitude cannot drop below 0\n",
    "\n",
    "            # Time ordering constraint (cannot cross left or right neighbor)\n",
    "            min_x = self.points[idx - 1][0] if idx > 0 else -2.0\n",
    "            max_x = self.points[idx + 1][0] if idx < len(self.points) - 1 else 125.0\n",
    "            new_x = np.clip(new_x, min_x + 0.05, max_x - 0.05)\n",
    "\n",
    "            self.points[idx] = [new_x, new_y]\n",
    "            self._show_tooltip(new_x, new_y)\n",
    "            self.update_canvas()\n",
    "\n",
    "        # 2. Moving an entire segment\n",
    "        elif self.selected_segment_idx is not None:\n",
    "            dx = event.xdata - self.drag_start[0]\n",
    "            dy = event.ydata - self.drag_start[1]\n",
    "            idx = self.selected_segment_idx\n",
    "\n",
    "            p1, p2 = self.points[idx], self.points[idx + 1]\n",
    "            # Verify non-negative altitude constraint\n",
    "            if p1[1] + dy >= 0 and p2[1] + dy >= 0:\n",
    "                # Verify neighbor order constraint\n",
    "                min_x = self.points[idx - 1][0] if idx > 0 else -2.0\n",
    "                max_x = self.points[idx + 2][0] if idx + 2 < len(self.points) else 125.0\n",
    "\n",
    "                if (p1[0] + dx > min_x) and (p2[0] + dx < max_x):\n",
    "                    self.points[idx] = [p1[0] + dx, p1[1] + dy]\n",
    "                    self.points[idx + 1] = [p2[0] + dx, p2[1] + dy]\n",
    "                    self.drag_start = (event.xdata, event.ydata)\n",
    "                    self.update_canvas()\n",
    "\n",
    "    def on_release(self, event):\n",
    "        self.selected_point_idx = None\n",
    "        self.selected_segment_idx = None\n",
    "        self.drag_start = None\n",
    "        self.tooltip.set_visible(False)\n",
    "        self.fig.canvas.draw_idle()\n",
    "\n",
    "    def _show_tooltip(self, x, y):\n",
    "        self.tooltip.xy = (x, y)\n",
    "        self.tooltip.set_text(f\"T: {x:.1f}m\\nAlt: {y:.1f}k\")\n",
    "        self.tooltip.set_visible(True)\n",
    "\n",
    "    def on_key_press(self, event):\n",
    "        if event.key in ['s', 'S']:\n",
    "            export_data = [\n",
    "                {\"time_min\": round(p[0], 2), \"altitude_kft\": round(p[1], 2), \"label\": lbl}\n",
    "                for p, lbl in zip(self.points, self.labels)\n",
    "            ]\n",
    "            with open(\"flight_profile.json\", \"w\") as f:\n",
    "                json.dump(export_data, f, indent=4)\n",
    "            print(\"Successfully saved updated points to 'flight_profile.json'!\")\n",
    "\n",
    "    def update_canvas(self):\n",
    "        pts = np.array(self.points)\n",
    "        self.line.set_data(pts[:, 0], pts[:, 1])\n",
    "        self.scatter.set_offsets(pts)\n",
    "        for i, ann in enumerate(self.text_artists):\n",
    "            ann.xy = (self.points[i][0], self.points[i][1])\n",
    "        self.fig.canvas.draw_idle()\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    editor = EnhancedFlightProfileEditor()\n",
    "    plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
